apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    name: voting-pod
    app: demo-app
spec:
  containers:
    - name: voting-pod
      image: dockersamples/examplevotingapp_vote
      ports:
       - containerPort: 80