apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    app: demo-app
spec:
  containers:
    - name: woker-pod
      image: dockersamples/examplevotingapp_worker
